#!/usr/bin/env node
const spl = require("./modules/spl/spl.js");
///////////////////////////////////////////////////////////////////////////////
// Set SPlectrum and client root directory, extract command string
var root = __dirname.split("/");
if (root.length === 1 ) root = root[0].split(`\\`);
const splRoot = root.join("/");
const commandString = process.argv.slice(2);
///////////////////////////////////////////////////////////////////////////////
const context = {   action: "spl/execute/initialise", consoleProgress: undefined,  consoleMode: "standard", // silent, standard, warning, verbose, debug
                    runtimeMode: "silent", cwd: splRoot, modules: "modules", TTL: 100 };
const action = "spl/app/process";
const batch = commandString;
const config = { batch: batch };
///////////////////////////////////////////////////////////////////////////////
var command = { headers: {}, value: {} }
spl.setContext ( command, null, context );
spl.setRequest ( command, "action", action );
spl.setConfig ( command, action, null, config );
///////////////////////////////////////////////////////////////////////////////
spl.moduleAction( command, "spl/execute/execute" );
// console.log("=== COMMAND OBJECT DUMP ===", JSON.stringify(command, null, 2), "========================");